name: CD

on: 
  push:
    branches:
      - prod
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurações do deploy
        run: |
          echo "📦 NOME DO PROJETO -> $(basename "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')"
          echo "🌿 STAGE DE DEPLOY -> $(basename "$GITHUB_REF")"
          echo "🌍 REGIÃO DE DEPLOY -> $AWS_REGION"

      - name: Definir as variáveis do Terraform
        run: |
          echo "TF_VAR_aws_region=$AWS_REGION" >> $GITHUB_ENV
          echo "TF_VAR_project_name=$(basename "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TF_VAR_stage=$(basename "$GITHUB_REF")" >> $GITHUB_ENV

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Validar a instalação do Terraform
        run: |
          cd iac
          terraform init
          echo "✅ Terraform instalado com sucesso!"

      - name: Fazer login na AWS
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_REGION"
          echo "✅ Login efetuado!"

      - name: Subir o ECR
        id: ecr
        run: |
            cd iac
            terraform apply -target="aws_ecr_repository.us-ecr" -var="lambda_image_uri=dummy" -auto-approve
            NEW_REPO_URL=$(terraform output -raw ecr-URL)
            echo "✅ Repositório criado: $NEW_REPO_URL"
            echo "repo_url=$NEW_REPO_URL" >> $GITHUB_OUTPUT


      - name: Criar o ambiente do container
        run: |
          cd app
          echo "stage=$(basename "$GITHUB_REF")" >> .env
          echo "✅ Ambiente criado."

      - name: Criar a imagem do container
        id: image 
        run: |
          TAG="$(basename "$GITHUB_REF")-$(date +%s)"
          docker build --platform linux/amd64 -t ${{ steps.ecr.outputs.repo_url }}:$TAG .
          echo "✅ Imagem criada."

      - name: Conectar ao ECR
        run: |
          REPO_URL="${{ steps.ecr.outputs.repo_url }}"
          REPO_HOST="${REPO_URL%%/*}"

          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_HOST

      - name: Subir a imagem
        run: |
          TAG=${{ steps.image.outputs.tag }}
          docker push ${{ steps.ecr.outputs.repo_url }}:$TAG
          echo "✅ Upload da imagem concluído."

      - name: Recuperar digest da imagem no ECR
        id: digest
        run: |
          TAG=${{ steps.image.outputs.tag }}
          REPO_URL="${{ steps.ecr.outputs.repo_url }}"
          REPO_NAME=$(basename "$REPO_URL")
              
          DIGEST=$(aws ecr describe-images \
            --repository-name "$REPO_NAME" \
            --region "$AWS_REGION" \
            --query "imageDetails[?contains(imageTags, \`$TAG\`)].imageDigest" \
            --output text 2>/dev/null)
              
          if [ -n "$DIGEST" ]; then
            echo "✅ Digest recuperado com sucesso: $DIGEST"
            echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          else
            echo "❌ Digest não encontrado para a tag '$STAGE'"
            exit 1
          fi

      - name: Criar infraestrutura com Terraform
        run: |
          cd iac
          terraform apply -var="lambda_image_uri=${{ steps.ecr.outputs.repo_url }}@${{ steps.digest.outputs.digest }}" -auto-approve
          echo "✅ Infra criada"
          echo "API INVOKE URL ---> $(terraform output -raw api-link)"
